export { ANYO_GEOMETRY_CONVENTIONS } from './core/conventions.js'
export { canonicalGeometryString, geometryDefinitionsEqual, hashGeometryDefinition } from './core/hashGeometry.js'
export { inspectGeometryDefinition, normalizeGeometryDefinition } from './core/normalizeGeometry.js'
export { GeometryCompiler, compileGeometry, createGeometryCompiler } from './core/GeometryCompiler.js'
export type { GeometryCompileContext, GeometryCompilerOptions, GeometryKindCompiler } from './core/GeometryCompiler.js'
export { GeometryCache } from './cache/GeometryCache.js'
export { generateNormals, generateTangents, generateUvs, applySurfacePolicy, normalizeSurfacePolicy } from './attributes/index.js'
export { computeGeometryBounds } from './bounds/computeBounds.js'
export { GeometryValidationError } from './validation/errors.js'
export { DEFAULT_GEOMETRY_SAFETY_LIMITS, resolveGeometrySafetyLimits } from './validation/limits.js'
export { finalizeGeometryMesh, inspectGeometryMesh } from './validation/validateMesh.js'
export { BUILTIN_GEOMETRY_KINDS, BUILTIN_GEOMETRY_KIND_NAMES, GEOMETRY_QUALITY_DEFAULTS } from './primitives/index.js'
export { normalizeProfile, contourPerimeter, pointInContour, signedContourArea } from './profiles/index.js'
export type { NormalizedProfile, ProfilePoint } from './profiles/index.js'
export { triangulateProfile } from './triangulation/index.js'
export type { TriangulatedProfile } from './triangulation/index.js'
export { offsetProfile } from './extrusion/index.js'
export { normalizeCurve, sampleCurve, sampleCurveAtDistance, computeCurveFrames, interpolateCurveFrame } from './curves/index.js'
export type { CurveFrame, CurvePoint3, NormalizedCurveDefinition, SampledCurve } from './curves/index.js'
export { layoutPathArray } from './path-array/index.js'
export { lowerArchitecture, normalizeWallOpenings, normalizeStandaloneDoorOpening, normalizeStandaloneWindowOpening } from './architecture/index.js'
export { CSG_OPERATIONS, booleanGeometryMeshes } from './csg/index.js'
export type { CsgOperation } from './csg/index.js'
export type * from './architecture/types.js'
export type { ArchitectureLowerOptions } from './architecture/index.js'
export { layoutGeometryArray, transformGeometryMesh, mergeGeometryMeshes } from './modifiers/index.js'
export type { GeometryArrayOptions, GeometryLocalTransform } from './modifiers/index.js'
export type { PathArrayOptions } from './path-array/index.js'
export type * from './types/index.js'
